-- MySQL Script generated by MySQL Workbench
-- Wed Mar  3 19:00:06 2021
-- Model: New Model    Version: 1.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema self_order_system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `self_order_system` ;

-- -----------------------------------------------------
-- Schema self_order_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `self_order_system` DEFAULT CHARACTER SET utf8 ;
USE `self_order_system` ;

-- -----------------------------------------------------
-- Table `self_order_system`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`user` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`user` (
  `id` VARCHAR(30) NOT NULL,
  `pw` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(13) NOT NULL,
  `profile_image` VARCHAR(255) NULL,
  `point` MEDIUMINT NOT NULL DEFAULT 0,
  `usercol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`restaurant_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`restaurant_category` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`restaurant_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`company` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`company` (
  `company_no` INT NOT NULL,
  `user_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`company_no`),
  INDEX `fk_company_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_company_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `self_order_system`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`restaurant` (
  `company_no` INT(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `profile_image` VARCHAR(255) NULL,
  `bookmark_count` MEDIUMINT NOT NULL DEFAULT 0,
  `score` FLOAT NOT NULL DEFAULT 0.0,
  `average_cooking_time` VARCHAR(45) NULL,
  `business_hours` VARCHAR(45) NULL,
  `closed_day` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `review_event_description` VARCHAR(255) NULL,
  `location_x` MEDIUMINT NOT NULL DEFAULT 0,
  `location_y` MEDIUMINT NOT NULL DEFAULT 0,
  `is_open` TINYINT(1) NOT NULL DEFAULT 0,
  `restaurant_category_id` INT NOT NULL,
  INDEX `fk_restaurant_restaurant_category_idx` (`restaurant_category_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `address_UNIQUE` (`address` ASC),
  PRIMARY KEY (`company_no`),
  CONSTRAINT `fk_restaurant_restaurant_category`
    FOREIGN KEY (`restaurant_category_id`)
    REFERENCES `self_order_system`.`restaurant_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_company1`
    FOREIGN KEY (`company_no`)
    REFERENCES `self_order_system`.`company` (`company_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`point_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`point_details` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`point_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `point` SMALLINT NOT NULL,
  `used_type` TINYINT(1) NOT NULL,
  `used_date` DATE NOT NULL,
  `user_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_point_details_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_point_details_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `self_order_system`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`menu_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`menu_category` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`menu_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `company_no` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_category_restaurant1_idx` (`company_no` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_menu_category_restaurant1`
    FOREIGN KEY (`company_no`)
    REFERENCES `self_order_system`.`restaurant` (`company_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`menu` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` MEDIUMINT NOT NULL,
  `image` VARCHAR(255) NULL,
  `info` VARCHAR(255) NULL,
  `is_soldout` TINYINT(1) NOT NULL DEFAULT 0,
  `company_no` INT(10) NOT NULL,
  `menu_category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_menu_restaurant1_idx` (`company_no` ASC),
  INDEX `fk_menu_menu_category1_idx` (`menu_category_id` ASC),
  CONSTRAINT `fk_menu_restaurant1`
    FOREIGN KEY (`company_no`)
    REFERENCES `self_order_system`.`restaurant` (`company_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_menu_category1`
    FOREIGN KEY (`menu_category_id`)
    REFERENCES `self_order_system`.`menu_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`menu_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`menu_option` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`menu_option` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` MEDIUMINT NOT NULL,
  `menu_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_option_menu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_menu_option_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `self_order_system`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`orders` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `payment_type` VARCHAR(45) NOT NULL,
  `total_price` MEDIUMINT NOT NULL,
  `request_term` VARCHAR(255) NULL,
  `user_id` VARCHAR(30) NOT NULL,
  `company_no` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_user1_idx` (`user_id` ASC),
  INDEX `fk_orders_restaurant1_idx` (`company_no` ASC),
  CONSTRAINT `fk_orders_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `self_order_system`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_restaurant1`
    FOREIGN KEY (`company_no`)
    REFERENCES `self_order_system`.`restaurant` (`company_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`order_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`order_menu` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`order_menu` (
  `orders_id` INT NOT NULL,
  `menu_option_id` INT NOT NULL,
  `count` TINYINT NOT NULL,
  PRIMARY KEY (`orders_id`, `menu_option_id`),
  INDEX `fk_order_menu_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_order_menu_menu_option1`
    FOREIGN KEY (`menu_option_id`)
    REFERENCES `self_order_system`.`menu_option` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_menu_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `self_order_system`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `self_order_system`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `self_order_system`.`review` ;

CREATE TABLE IF NOT EXISTS `self_order_system`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `score` MEDIUMINT NOT NULL,
  `image` VARCHAR(255) NULL,
  `orders_id` INT NOT NULL,
  `user_id` VARCHAR(30) NOT NULL,
  `company_no` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_orders1_idx` (`orders_id` ASC),
  INDEX `fk_review_user1_idx` (`user_id` ASC),
  INDEX `fk_review_restaurant1_idx` (`company_no` ASC),
  CONSTRAINT `fk_review_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `self_order_system`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `self_order_system`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_restaurant1`
    FOREIGN KEY (`company_no`)
    REFERENCES `self_order_system`.`restaurant` (`company_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
